---
title: 'The Impact of VAR: Balancing Technology and Tradition in Soccer'
author: "Keegan Burr"
date: "10/25/24"
output:
  pdf_document: default
fontsize: 12pt
header-includes:
  - \usepackage{setspace}
  - \onehalfspacing
---

Soccer, known to many as football, is one of the most popular sports in the world. Clubs, fans, leagues, sponsors, and broadcasters invest billions of dollars into the sport each year. Fans are passionate and stakes are high. The games mean so much to so many and because of this, the game is ever-evolving. One of the most significant changes in the sport's history was the implementation of Video Assistant Referees, also known as VAR. According to the English Premier League, VAR is “a qualified referee who watches the match via a number of screens and can view slow-motion replays, enabling them to advise the on-field referee." It was initially introduced to be used only in the event of a ‘clear and obvious error,' but since VAR's introduction, the system has sparked constant debate. Many question the need for technology, in a beloved sport that has been played for hundreds of years. In a study done by Jack Kenyon Brown, Brown examines how VAR has influenced what is considered the best league in the world, the English Premier League.

The data used within this study was publicly available soccer data from a website called FBref.com. To collect the data, a web scraper was utilized from the XLM and RCurl packages in RStudio. After, a variety of game statistics for both home and away teams were collected for every Premier League game from the 2014/2015 season through the 2023/2024 season. This would account for 3800 games, as there are 380 games played in a season. Brown would then go on to choose ten variables that he felt were most significant/may be the most impacted by the implementation of VAR. For context, these variables were goals, fouls, penalty kicks awarded, penalty kicks scored, shots, offsides, red cards, yellow cards, tackles, and interceptions. 

To ensure the validity of the methods used for the study, Brown started by testing for two key assumptions, normality of the data and equality of variance. The reason he chose to look into these is because these assumptions are often used for many traditional statistical methods like T-tests. To check for normality, Brown used Shapiro-Wilk, Anderson-Darling, and Kolmogorov-Smirnov tests. Each of these tests evaluated whether the distribution of the data significantly deviated from a normal distribution. Deviations in normality can affect the accuracy of the results, as data that is not normally distributed can cause T-tests to produce misleading conclusions. Additionally, Brown created histograms to provide a better understanding visually for the reader. Altogether, the following test confirmed that none of the 10 variables of interest followed a strict normal distribution at the 0.05 significance level. This would come as surprising as the central limit theorem suggests large sample sizes usually lead to approximately normal distributions. Then for the equal variance assumption, Breusch-Pagan and Levene’s tests were used to help determine if the variability in the data is consistent across different groups. The Breusch-Pagan test was chosen as it is sensitive to any heteroscedasticity (unequal spread of variances), while Levene’s test assesses whether variances are equal across groups. The tests confirmed only two of the ten variables of interest, offsides, and interceptions, violated the assumption (at a significance level of 0.01). 

Given the violations, and particularity of normality in the variables, in addition to a standard T-test, Brown would choose to use Welch's T-test. Welch's T-test, is a statistical method that does not assume equal variance. It was chosen to account for the two violations of equal variance. Then to further validate the results, Brown performed non-parametric Mann-Whitney U-tests. The Mann-Whitney U-test is useful in this context because it does not assume normality or equal variances, providing an even more flexible analysis. Finally, to further address the violations of the data, Brown also ran a generalized linear model (GLM) with Negative Binomial components. This choice would allow us to see the model response to variables that exhibit these non-normal distributions. The negative binomial component was chosen as it is useful in handling the type of skewed data that we would find in our dataset.

In the end, Brown hoped the above tests resulting in p-values would together provide a 'majority consensus' as to whether there were statistically significant differences in the different variables of interest. While it is noted that there are many mixed conclusions on the impact of VAR across different leagues, based on Brown's study in the Premier League, his analysis allowed us to discover many immediate, intermediate, and long-term statistically significant differences in the selected game statistics for before and after the implementation of VAR. Based on the three selected time frames (a 1-year difference, a 3-year difference, and a 5-year difference) significant findings included increases in fouls, tackles, goals, penalty kicks, and yellow cards, alongside decreases in offsides and interceptions. However, it is important to note there have been other rule changes over the years such as added time which may have influenced significant differences. So despite some statistically significant differences, Brown determined it would be statistically irresponsible to conclude that VAR has had a drastic effect on the Premier League based on confounding variables.

While the introduction of VAR has brought about significant differences in refereeing, its implementation has also raised an important normative question, has the reliance on technology worsened the fairness and integrity of the game? Although VAR was designed with the intent of making refereeing 'fairer,' we must ask whether its implementation has actually created new inequalities. This brings us to a critical distinction between fairness as equity and fairness as equality. Fairness as equality would suggest that all teams and leagues should have access to the same resources and technology to ensure a level playing field. However, fairness as equity considers that different contexts require different levels of support, meaning that certain teams or leagues may need more resources to achieve the same standard of fairness. The fact that only the wealthiest leagues can afford VAR creates a system where some benefit from heightened accuracy and others are left behind, thus creating global inequalities in refereeing standards. 

From the perspective of John Rawls' concept of 'justice as fairness,' these disparities in resource allocation would be ethically problematic. Rawls argued that when inequalities exist, they should be structured in a way that they work to the advantage of the most vulnerable. In the context of soccer, this would mean that access to VAR or similar technological aids should not only be limited to the wealthiest leagues but should be either distributed in a way that benefits those without the system or removed entirely. For example, if only certain leagues or tournaments have access to VAR, measures should be taken to either provide similar resources to less wealthy leagues or adjust international competitions to account for the imbalance. Without such considerations, the integrity of soccer as a global sport could be compromised, as teams from underprivileged leagues face disadvantages not because of skill or ability, but due to a lack of access to technology.

The thing is technology has always forced industries to evolve. We've seen it in the banking industry where many banks transitioned their banking online. We've seen it in other sports like GPS tracking in rugby and PylonCam in American football. Technology has led to evolution, but referees have one of the key roles in any sport. A referee is obliged to make unbiased decisions. Soccer has long embraced human error as part of the game and some iconic moments have been the result of difficult decisions made by referees. For better or for worse, VAR changes referees' roles by reducing the role of human judgment in these crucial decisions. According to Kant, using the VAR system could be justified as it serves to enhance fairness and accuracy, by aligning with the moral obligations of referees. While it may seem like a positive development, many question whether it causes football to lose its human element raising the dilemma, should perfect decision-making come at the cost of changing the traditions of the historic game which has made it so unpredictable. Some worry this might eventually lead us down a slippery slope of over-reliance on technology.

The justification for VAR’s introduction was its potential to make decision-making more transparent and trustworthy, however, in practice the reasoning behind VAR decision-making can still be ambiguous. There are times when even after multiple replays the decision can remain unclear, but when people are left baffled by outcomes made by referees, the fairness of the game is called into question. Rather than creating transparency, VAR may have led to more confusion and controversy over the rules of the game. This is why we need to understand the impact of VAR on the global sport. Is the increase in accurate decision-making significant enough to completely change the ways of such a historic sport? On top of that, if a system that is supposed to create transparency, instead leads to mistrust in the officiating of the game, it seriously brings into question if VAR is worth risking the integrity of the sport.

\newpage

References

Galily, Yair. “From Sport Psychology to Action Philosophy: Immanuel Kant and the Case of Video Assistant Referees.” *Behavioral sciences (Basel, Switzerland)* vol. 14,4 291. 1 Apr. 2024, doi:10.3390/bs14040291

Brown, Jack Kenyon. *The Impact of Video Assistant Referee (VAR) on the English Premier League*, 1 June 2024, digitalcommons.calpoly.edu/cgi/viewcontent.cgi?params=/context/theses/article/4475/&path_info=The_Impact_of_Video_Assistant_Referee__VAR__on_the_English_Premier_League.pdf. 

“Var - Frequently Asked Questions.” *Premier League*, 1 June 2020, www.premierleague.com/news/1293321?os=fuzzscan0xxtr&ref=app#. 

Bobbitt, Zach. “The Breusch-Pagan Test: Definition & Example.” *Statology*, 25 Jan. 2022, www.statology.org/breusch-pagan-test/. 

DATAtab Team (2024). "DATAtab: Normality test". *DATAtab e.U. Graz, Austria.* URL https://datatab.net/tutorial/test-of-normality


